# -*- coding: utf-8 -*-
"""AdvertisingSales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DZdDDWD_HrFwl9XwvGodCGGzhZBRaULt
"""

import streamlit as st
import pandas as pd
import pickle

st.write("""
# Advertising Sales Prediction App

This app predicts the **Sales** for type of advertising stratergy!
""")

st.sidebar.header('User Input Parameters')

def user_input_features():
    tv = st.sidebar.slider('TV', 0.7, 297, 100)
    radio = st.sidebar.slider('Radio', 0, 50, 15)
    newspaper = st.sidebar.slider('Newspaper', 0.3, 114, 20)
    data = {'TV': tv,
            'Radio': radio,
            'Newspaper': newspaper}
    features = pd.DataFrame(data, index=[0])
    return features

df = user_input_features()

st.subheader('User Input parameters')
st.write(df)

#loaded_model = pickle.load(open("advertising_model.h5", "rb"))

#prediction = loaded_model.predict(df)

st.subheader('Prediction')
#st.write(prediction)
